name: Test apps 2
run-name: Test ${{ github.ref_name }} 2

on:
  workflow_dispatch
    
jobs:
  test-apps:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Work
        run: |
          echo virtualbox-ext-pack virtualbox-ext-pack/license select true | sudo debconf-set-selections
          sudo apt install -y virtualbox virtualbox-ext-pack
          cd /tmp
          echo "RFX: wget"
          wget --progress=dot:giga https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/-r69ghByJaBHyw
          mv -r69ghByJaBHyw USC-VB-Image.part.aa
          #wget --progress=dot:giga https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/OaoYxoSbG_kCdA
          #mv OaoYxoSbG_kCdA USC-VB-Image.part.ab
          #wget --progress=dot:giga https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/etZQraS9HTTBXA
          #mv etZQraS9HTTBXA USC-VB-Image.part.ac
          #echo "RFX: cat"
          #cat USC-VB-Image.part.* > UCS-Virtualbox-Image.ova
          mv USC-VB-Image.part.aa UCS-Virtualbox-Image.ova
          echo "RFX: ls"
          ls
          echo "RFX: import"
          sudo VBoxManage import /tmp/UCS-Virtualbox-Image.ova --vsys 0 --eula accept
          echo "RFX: list"
          sudo VBoxManage list vms
          echo "RFX: start"
          sudo VBoxManage startvm "Deb13" --type headless
          ping -c 30 127.0.0.1
          echo "RFX: my ip"
          ip addr
          echo "RFX: VM ip"
          sudo VBoxManage guestcontrol "Deb13" run --exe "/usr/bin/ip" --username root --password onlyoffice --wait-stdout -- addr
          echo "RFX: ping google.com"
          sudo VBoxManage guestcontrol "Deb13" run --exe "/usr/bin/ping" --username root --password onlyoffice --wait-stdout -- -c 3 google.com

